// GENERATED by tools/cook-themes.ts — do not edit.
// Values: themes-src/sheru/aqua.json (sheru 49d35621ae5b) + themes-src/density.ts
// Rules:  themes-src/paint/aqua.ts
import type { ThemeSkin } from "../skin.ts";

export const aquaSkin: ThemeSkin = {
  "id": "aqua",
  "name": "Aqua",
  "classes": {
    "desktop": "w-full h-full flex-col justify-center items-center bg-[#3f6fbe]",
    "window": "w-[464] h-[256] flex-col rounded-[8] border-[#0000004d] shadow-lg bg-[#e8e8e8]",
    "window-frame": "flex-1 flex-col",
    "window-frame-edge": "absolute inset-0",
    "titlebar": "flex-row items-center justify-between h-[18] mb-[1]",
    "titlebar/inactive": "flex-row items-center justify-between h-[18] mb-[1]",
    "title": "pt-[0] pr-[8] pb-[0] pl-[8] text-xs font-bold text-[#1e1e1e]",
    "title/inactive": "pt-[0] pr-[8] pb-[0] pl-[8] text-xs font-bold text-[#7f7f7f]",
    "controls": "flex-row items-center pt-[0] pr-[8] pb-[0] pl-[8] gap-[8]",
    "control": "w-[14] h-[14] flex-col justify-center items-center rounded-[7]",
    "control/close": "w-[14] h-[14] flex-col justify-center items-center rounded-[7]",
    "toolbar": "flex-row items-center h-[26] pt-[0] pr-[4] pb-[0] pl-[4] bg-gradient-to-b from-[#f5f5f5] to-[#e8e8e8] gap-[4]",
    "toolbar-button": "flex-col justify-center items-center h-[22] pt-[0] pr-[10] pb-[0] pl-[10] rounded-[11] border-[#9a9a9a] focus:bg-gradient-to-b focus:from-[#ffffff] focus:to-[#e4eefb] text-xs text-[#000000] min-w-[22] active:bg-[#c6c6c6]",
    "breadcrumbs": "flex-1 flex-row items-center text-xs text-[#5d5d5d]",
    "breadcrumb": "h-[18] pt-[0] pr-[6] pb-[0] pl-[6] rounded-[9] focus:bg-[#00000014] text-xs text-[#000000]",
    "split": "flex-1 flex-row p-[2] gap-[2] overflow-hidden",
    "sidebar": "flex-col w-[96] pt-[6] pr-[0] pb-[6] pl-[0] bg-[#dee3e9] overflow-hidden",
    "sidebar-heading": "flex-row items-center h-[16] pt-[0] pr-[12] pb-[0] pl-[12] text-xs font-bold text-[#5d5d5d] mb-[2] shrink-0",
    "sidebar-item": "flex-row items-center h-[17] pt-[0] pr-[12] pb-[0] pl-[12] focus:bg-gradient-to-b focus:from-[#6c9ef0] focus:to-[#3875d7] text-xs text-[#1e1e1e] shrink-0",
    "file-list": "flex-1 flex-col bg-[#ffffff] overflow-hidden",
    "file-list-header": "flex-row items-center h-[17] shrink-0",
    "file-list-col": "flex-row items-center h-full pt-[0] pr-[6] pb-[0] pl-[6] text-xs text-[#4a4a4a]",
    "file-list-col/sorted": "flex-row items-center h-full pt-[0] pr-[6] pb-[0] pl-[6] text-xs text-[#4a4a4a]",
    "segment": "flex-col justify-center items-center h-[22] w-[33] rounded-[11] border-[#9a9a9a] active:bg-[#c6c6c6]",
    "segment/selected": "flex-col justify-center items-center h-[22] w-[33] rounded-[11] border-[#9a9a9a]",
    "file-row": "flex-row items-center h-[17] pt-[0] pr-[2] pb-[0] pl-[2] focus:bg-gradient-to-b focus:from-[#6c9ef0] focus:to-[#3875d7] shrink-0",
    "status-bar": "flex-row items-center justify-center h-[20] p-[2] bg-[#e8e8e8] gap-[2] shrink-0",
    "status-item": "flex-row items-center h-full pt-[0] pr-[6] pb-[0] pl-[6] text-xs text-[#5d5d5d]",
    "button": "h-[22] flex-col justify-center items-center pt-[0] pr-[10] pb-[0] pl-[10] rounded-[11] border-[#9a9a9a] focus:bg-gradient-to-b focus:from-[#ffffff] focus:to-[#e4eefb] text-xs text-[#000000] active:bg-[#c6c6c6]"
  },
  "metrics": {
    "windowFrameW": 0,
    "controlW": 14,
    "controlH": 14
  },
  "glyphs": {
    "folder": "glyphs/aqua-icon-folder.png",
    "file": "glyphs/aqua-icon-file.png",
    "file-md": "glyphs/aqua-icon-file-md.png",
    "file-png": "glyphs/aqua-icon-file-png.png",
    "file-pbp": "glyphs/aqua-icon-file-pbp.png",
    "file-xlsx": "glyphs/aqua-icon-file-xlsx.png",
    "file-txt": "glyphs/aqua-icon-file-txt.png",
    "file-pdf": "glyphs/aqua-icon-file-pdf.png",
    "file-json": "glyphs/aqua-icon-file-json.png"
  },
  "strips": {
    "titlebar": "strips/aqua-titlebar.png",
    "titlebar/inactive": "strips/aqua-titlebar_inactive.png",
    "toolbar-button": "strips/aqua-toolbar-button.png",
    "file-list-header": "strips/aqua-file-list-header.png",
    "file-list-col/sorted": "strips/aqua-file-list-col_sorted.png",
    "segment": "strips/aqua-segment.png",
    "segment/selected": "strips/aqua-segment_selected.png",
    "button": "strips/aqua-button.png"
  },
  "fonts": {
    "regular": "shell:font.inter.0",
    "bold": "shell:font.inter.7"
  },
  "chrome": {
    "side": "left",
    "order": [
      "close",
      "minimize",
      "zoom"
    ]
  }
};
