// GENERATED by tools/cook-themes.ts — do not edit.
// Values: themes-src/sheru/win7.json (sheru 49d35621ae5b) + themes-src/density.ts
// Rules:  themes-src/paint/win7.ts
import type { ThemeSkin } from "../skin.ts";

export const win7Skin: ThemeSkin = {
  "id": "win7",
  "name": "Seven",
  "classes": {
    "desktop": "w-full h-full flex-col justify-center items-center bg-[#2c5d8f]",
    "window": "w-[464] h-[256] flex-col p-[3] rounded-[6] border-[#1c3046c7]",
    "window-frame": "flex-1 flex-col border-[#314c6aa6] bg-gradient-to-b from-[#f4f6f8] to-[#ebeef1]",
    "window-frame-edge": "absolute inset-0",
    "titlebar": "flex-row items-center justify-between h-[18]",
    "titlebar/inactive": "flex-row items-center justify-between h-[18]",
    "title": "pt-[0] pr-[8] pb-[0] pl-[8] text-xs text-[#1e1e1e]",
    "title/inactive": "pt-[0] pr-[8] pb-[0] pl-[8] text-xs text-[#56606a]",
    "controls": "flex-row items-center gap-0",
    "control": "w-[30] h-[19] flex-col justify-center items-center focus:bg-[#96c9ed80] active:bg-[#96b4ce8c]",
    "control/close": "w-[46] h-[19] flex-col justify-center items-center focus:bg-[#dd463b] active:bg-[#a52c23]",
    "toolbar": "flex-row items-center h-[26] pt-[0] pr-[4] pb-[0] pl-[4] bg-gradient-to-b from-[#fdfeff] to-[#e6f0fa] gap-[4]",
    "toolbar-button": "flex-col justify-center items-center h-[22] pt-[0] pr-[5] pb-[0] pl-[5] rounded-[3] focus:bg-gradient-to-b focus:from-[#eaf6fd] focus:to-[#a7d9f5] text-xs text-[#1e1e1e] min-w-[22] active:bg-[#98d1ef]",
    "breadcrumbs": "flex-1 flex-row items-center h-[20] pt-[0] pr-[2] pb-[0] pl-[2] rounded-[2] border-[#abadb3] bg-[#ffffff]",
    "breadcrumb": "pt-[0] pr-[7] pb-[0] pl-[7] rounded-[2] focus:bg-gradient-to-b focus:from-[#eaf6fd] focus:to-[#a7d9f5] text-xs text-[#1e1e1e] active:bg-[#98d1ef]",
    "split": "flex-1 flex-row p-[2] gap-[2] overflow-hidden",
    "sidebar": "flex-col w-[96] p-[2] bg-[#f7fbff] overflow-hidden",
    "sidebar-heading": "flex-row items-center h-[16] pt-[0] pr-[6] pb-[0] pl-[6] text-xs text-[#6d6d6d] mb-[2] shrink-0",
    "sidebar-item": "flex-row items-center h-[17] pt-[0] pr-[4] pb-[0] pl-[12] rounded-[2] focus:bg-gradient-to-b focus:from-[#ebf4fc] focus:to-[#cfe4f7] shrink-0",
    "file-list": "flex-1 flex-col bg-[#ffffff] overflow-hidden",
    "file-list-header": "flex-row items-center h-[17] bg-[#ffffff] shrink-0",
    "file-list-col": "flex-row items-center h-full pt-[0] pr-[6] pb-[0] pl-[6] border-[#e5e5e5] focus:bg-gradient-to-b focus:from-[#f4f9fd] focus:to-[#dceefb] text-xs text-[#454545]",
    "file-list-col/sorted": "flex-row items-center h-full pt-[0] pr-[6] pb-[0] pl-[6] border-[#e5e5e5] bg-gradient-to-b from-[#f4f9fd] to-[#dceefb] text-xs text-[#454545]",
    "segment": "flex-col justify-center items-center h-[22] w-[33] border-[#707070] focus:bg-gradient-to-b focus:from-[#eaf6fd] focus:to-[#a7d9f5] active:bg-[#98d1ef]",
    "segment/selected": "flex-col justify-center items-center h-[22] w-[33] border-[#2c628b]",
    "file-row": "flex-row items-center h-[17] pt-[0] pr-[2] pb-[0] pl-[2] rounded-[2] focus:bg-gradient-to-b focus:from-[#dcebfc] focus:to-[#c1dbfc] shrink-0",
    "status-bar": "flex-row items-center h-[20] p-[2] bg-gradient-to-b from-[#f2f7fc] to-[#e0ebf6] gap-[2] shrink-0",
    "status-item": "flex-row items-center h-full pt-[0] pr-[6] pb-[0] pl-[6] text-xs text-[#6d6d6d]",
    "button": "h-[22] flex-col justify-center items-center pt-[0] pr-[10] pb-[0] pl-[10] rounded-[3] border-[#707070] focus:bg-gradient-to-b focus:from-[#eaf6fd] focus:to-[#a7d9f5] text-xs text-[#1e1e1e] active:bg-[#98d1ef]"
  },
  "metrics": {
    "windowFrameW": 3,
    "controlW": 30,
    "controlH": 19
  },
  "glyphs": {
    "minimize": "glyphs/win7-minimize.png",
    "zoom": "glyphs/win7-zoom.png",
    "close": "glyphs/win7-close.png",
    "folder": "glyphs/win7-icon-folder.png",
    "file": "glyphs/win7-icon-file.png",
    "file-md": "glyphs/win7-icon-file-md.png",
    "file-png": "glyphs/win7-icon-file-png.png",
    "file-pbp": "glyphs/win7-icon-file-pbp.png",
    "file-xlsx": "glyphs/win7-icon-file-xlsx.png",
    "file-txt": "glyphs/win7-icon-file-txt.png",
    "file-pdf": "glyphs/win7-icon-file-pdf.png",
    "file-json": "glyphs/win7-icon-file-json.png"
  },
  "strips": {
    "window": "strips/win7-window.png",
    "titlebar": "strips/win7-titlebar.png",
    "titlebar/inactive": "strips/win7-titlebar_inactive.png",
    "segment": "strips/win7-segment.png",
    "segment/selected": "strips/win7-segment_selected.png",
    "button": "strips/win7-button.png"
  },
  "fonts": {
    "regular": "shell:font.inter.0",
    "bold": "shell:font.inter.7"
  },
  "chrome": {
    "side": "right",
    "order": [
      "minimize",
      "zoom",
      "close"
    ]
  }
};
