// GENERATED by tools/cook-themes.ts — do not edit.
// Values: themes-src/sheru/win98.json (sheru 49d35621ae5b) + themes-src/density.ts
// Rules:  themes-src/paint/win98.ts
import type { ThemeSkin } from "../skin.ts";

export const win98Skin: ThemeSkin = {
  id: "win98",
  name: "98",
  classes: {
      "desktop": "w-full h-full flex-col justify-center items-center bg-[#008080]",
      "window": "w-[464] h-[256] flex-col p-[3] bg-[#c0c0c0]",
      "window-frame": "flex-1 flex-col",
      "window-frame-edge": "absolute inset-0 bevel-[#dfdfdf,#000000,#ffffff,#808080]",
      "titlebar": "flex-row items-center justify-between h-[18] pt-[2] pr-[2] pb-[2] pl-[3] bg-gradient-to-r from-[#000080] to-[#1084d0] mb-[1]",
      "titlebar/inactive": "flex-row items-center justify-between h-[18] pt-[2] pr-[2] pb-[2] pl-[3] bg-gradient-to-r from-[#808080] to-[#b5b5b5] mb-[1]",
      "title": "pt-[0] pr-[4] pb-[0] pl-[2] text-xs font-bold text-[#ffffff]",
      "title/inactive": "pt-[0] pr-[4] pb-[0] pl-[2] text-xs font-bold text-[#c0c0c0]",
      "controls": "flex-row items-center gap-0",
      "control": "w-[16] h-[14] flex-col justify-center items-center bg-[#c0c0c0] bevel-[#ffffff,#000000,#dfdfdf,#808080] active:bevel-[#000000,#ffffff,#808080,#dfdfdf]",
      "control/close": "w-[16] h-[14] flex-col justify-center items-center bg-[#c0c0c0] bevel-[#ffffff,#000000,#dfdfdf,#808080] active:bevel-[#000000,#ffffff,#808080,#dfdfdf] ml-[2]",
      "button": "h-[22] flex-col justify-center items-center pt-[0] pr-[10] pb-[0] pl-[10] bg-[#c0c0c0] bevel-[#ffffff,#000000,#dfdfdf,#808080] active:bevel-[#000000,#ffffff,#808080,#dfdfdf] text-xs text-[#000000]"
  },
  metrics: {"windowFrameW":3,"controlW":16,"controlH":14},
};
