// GENERATED by tools/cook-themes.ts — do not edit.
// Values: themes-src/sheru/win98.json (sheru 49d35621ae5b) + themes-src/density.ts
// Rules:  themes-src/paint/win98.ts
import type { ThemeSkin } from "../skin.ts";

export const win98Skin: ThemeSkin = {
  id: "win98",
  name: "98",
  classes: {
      "desktop": "w-full h-full flex-col justify-center items-center bg-[#008080]",
      "window": "w-[464] h-[256] flex-col p-[3] bg-[#c0c0c0]",
      "window-frame": "flex-1 flex-col",
      "window-frame-edge": "absolute inset-0 bevel-[#dfdfdf,#000000,#ffffff,#808080]",
      "titlebar": "flex-row items-center justify-between h-[18] pt-[2] pr-[2] pb-[2] pl-[3] bg-gradient-to-r from-[#000080] to-[#1084d0] mb-[1]",
      "titlebar/inactive": "flex-row items-center justify-between h-[18] pt-[2] pr-[2] pb-[2] pl-[3] bg-gradient-to-r from-[#808080] to-[#b5b5b5] mb-[1]",
      "title": "pt-[0] pr-[4] pb-[0] pl-[2] text-xs font-bold text-[#ffffff]",
      "title/inactive": "pt-[0] pr-[4] pb-[0] pl-[2] text-xs font-bold text-[#c0c0c0]",
      "controls": "flex-row items-center gap-0",
      "control": "w-[16] h-[14] flex-col justify-center items-center bg-[#c0c0c0] bevel-[#ffffff,#000000,#dfdfdf,#808080] active:bevel-[#000000,#ffffff,#808080,#dfdfdf]",
      "control/close": "w-[16] h-[14] flex-col justify-center items-center bg-[#c0c0c0] bevel-[#ffffff,#000000,#dfdfdf,#808080] active:bevel-[#000000,#ffffff,#808080,#dfdfdf] ml-[2]",
      "toolbar": "flex-row items-center h-[26] pt-[0] pr-[4] pb-[0] pl-[4] bg-[#c0c0c0] bevel-[#ffffff,#808080] gap-[4]",
      "toolbar-button": "flex-col justify-center items-center h-[22] pt-[0] pr-[5] pb-[0] pl-[5] focus:bevel-[#ffffff,#808080] active:bevel-[#808080,#ffffff] text-xs font-bold text-[#000000] min-w-[22]",
      "breadcrumbs": "flex-1 flex-row items-center h-[18] pt-[2] pr-[4] pb-[2] pl-[4] bg-[#ffffff] bevel-[#808080,#ffffff,#000000,#dfdfdf]",
      "breadcrumb": "pt-[0] pr-[3] pb-[0] pl-[3] text-xs text-[#000000]",
      "split": "flex-1 flex-row p-[2] gap-[2] overflow-hidden",
      "sidebar": "flex-col w-[96] p-[2] bg-[#ffffff] bevel-[#808080,#ffffff,#000000,#dfdfdf] overflow-hidden",
      "sidebar-heading": "flex-row items-center h-[16] pt-[0] pr-[6] pb-[0] pl-[6] bg-[#c0c0c0] bevel-[#ffffff,#808080] text-xs text-[#000000] mb-[2] shrink-0",
      "sidebar-item": "flex-row items-center h-[17] pt-[0] pr-[4] pb-[0] pl-[4] focus:bg-[#000080] shrink-0",
      "file-list": "flex-1 flex-col bg-[#ffffff] bevel-[#808080,#ffffff,#000000,#dfdfdf] overflow-hidden",
      "file-list-header": "flex-row items-center h-[17] shrink-0",
      "file-list-col": "flex-row items-center h-full pt-[0] pr-[6] pb-[0] pl-[6] bg-[#c0c0c0] bevel-[#ffffff,#000000,#dfdfdf,#808080] text-xs text-[#000000]",
      "file-list-col/sorted": "flex-row items-center h-full pt-[1] pr-[5] pb-[0] pl-[7] bg-[#c0c0c0] bevel-[#000000,#ffffff,#808080,#dfdfdf] text-xs text-[#000000]",
      "segment": "flex-col justify-center items-center h-[22] w-[33] bg-[#c0c0c0] bevel-[#ffffff,#000000,#dfdfdf,#808080]",
      "segment/selected": "flex-col justify-center items-center h-[22] w-[33] bg-[#c0c0c0] bevel-[#000000,#ffffff,#808080,#dfdfdf]",
      "file-row": "flex-row items-center h-[17] pt-[0] pr-[2] pb-[0] pl-[2] focus:bg-[#000080] shrink-0",
      "status-bar": "flex-row items-center h-[20] p-[2] bg-[#c0c0c0] gap-[2] shrink-0",
      "status-item": "flex-row items-center h-full pt-[0] pr-[6] pb-[0] pl-[6] bevel-[#808080,#ffffff]",
      "button": "h-[22] flex-col justify-center items-center pt-[0] pr-[10] pb-[0] pl-[10] bg-[#c0c0c0] bevel-[#ffffff,#000000,#dfdfdf,#808080] active:bevel-[#000000,#ffffff,#808080,#dfdfdf] text-xs text-[#000000]"
  },
  metrics: {"windowFrameW":3,"controlW":16,"controlH":14},
};
