// GENERATED by tools/cook-themes.ts — do not edit.
// Values: themes-src/sheru/winxp.json (sheru 49d35621ae5b) + themes-src/density.ts
// Rules:  themes-src/paint/winxp.ts
import type { ThemeSkin } from "../skin.ts";

export const winxpSkin: ThemeSkin = {
  "id": "winxp",
  "name": "XP",
  "classes": {
    "desktop": "w-full h-full flex-col justify-center items-center bg-[#004e98]",
    "window": "w-[464] h-[256] flex-col p-[3] border-[#0831d9] bg-[#0855dd]",
    "window-frame": "flex-1 flex-col bg-[#ece9d8]",
    "window-frame-edge": "absolute inset-0",
    "titlebar": "flex-row items-center justify-between h-[18] pt-[0] pr-[5] pb-[0] pl-[8]",
    "titlebar/inactive": "flex-row items-center justify-between h-[18] pt-[0] pr-[5] pb-[0] pl-[8]",
    "title": "pt-[0] pr-[8] pb-[0] pl-[0] text-xs font-bold text-[#ffffff]",
    "title/inactive": "pt-[0] pr-[8] pb-[0] pl-[0] text-xs font-bold text-[#d8e4f8]",
    "controls": "flex-row items-center gap-[2]",
    "control": "w-[21] h-[21] flex-col justify-center items-center rounded-[3]",
    "control/close": "w-[21] h-[21] flex-col justify-center items-center rounded-[3]",
    "toolbar": "flex-row items-center h-[26] pt-[0] pr-[4] pb-[0] pl-[4] gap-[4]",
    "toolbar-button": "flex-col justify-center items-center h-[22] pt-[0] pr-[8] pb-[0] pl-[8] rounded-[3] focus:bg-[#fff0cf] text-xs text-[#000000] min-w-[22] active:bg-[#e3e0d8]",
    "breadcrumbs": "flex-1 flex-row items-center h-[20] pt-[0] pr-[5] pb-[0] pl-[5] border-[#7f9db9] bg-[#ffffff]",
    "breadcrumb": "pt-[1] pr-[3] pb-[1] pl-[3] text-xs text-[#000000]",
    "split": "flex-1 flex-row p-[2] gap-[2] overflow-hidden",
    "sidebar": "flex-col w-[96] p-[2] overflow-hidden",
    "sidebar-heading": "flex-row items-center h-[16] pt-[0] pr-[6] pb-[0] pl-[6] text-xs font-bold text-[#215dc6] mb-[2] shrink-0",
    "sidebar-item": "flex-row items-center h-[17] pt-[0] pr-[4] pb-[0] pl-[4] focus:bg-[#316ac5] shrink-0",
    "file-list": "flex-1 flex-col bg-[#ffffff] overflow-hidden",
    "file-list-header": "flex-row items-center h-[17] bg-[#ebeadb] shrink-0",
    "file-list-col": "flex-row items-center h-full pt-[0] pr-[6] pb-[0] pl-[6] border-[#d8d7bf] bg-[#ebeadb] text-xs text-[#000000]",
    "file-list-col/sorted": "flex-row items-center h-full pt-[0] pr-[6] pb-[0] pl-[6] border-[#d8d7bf] bg-[#ece9d8] text-xs text-[#000000]",
    "segment": "flex-col justify-center items-center h-[22] w-[33] rounded-[3] border-[#003c74]",
    "segment/selected": "flex-col justify-center items-center h-[22] w-[33] rounded-[3] border-[#003c74]",
    "file-row": "flex-row items-center h-[17] pt-[0] pr-[2] pb-[0] pl-[2] focus:bg-[#316ac5] shrink-0",
    "status-bar": "flex-row items-center h-[20] p-[2] bg-[#ece9d8] gap-[2] shrink-0",
    "status-item": "flex-row items-center h-full pt-[0] pr-[8] pb-[0] pl-[8] bevel-[#aca899,#f1efe2] text-xs text-[#000000]",
    "button": "h-[22] flex-col justify-center items-center pt-[0] pr-[10] pb-[0] pl-[10] rounded-[3] border-[#003c74] text-xs text-[#000000] active:bg-[#e3e0d8]"
  },
  "metrics": {
    "windowFrameW": 3,
    "controlW": 21,
    "controlH": 21
  },
  "glyphs": {
    "minimize": "glyphs/winxp-minimize.png",
    "zoom": "glyphs/winxp-zoom.png",
    "close": "glyphs/winxp-close.png",
    "folder": "glyphs/winxp-icon-folder.png",
    "file": "glyphs/winxp-icon-file.png",
    "file-md": "glyphs/winxp-icon-file-md.png",
    "file-png": "glyphs/winxp-icon-file-png.png",
    "file-pbp": "glyphs/winxp-icon-file-pbp.png",
    "file-xlsx": "glyphs/winxp-icon-file-xlsx.png",
    "file-txt": "glyphs/winxp-icon-file-txt.png",
    "file-pdf": "glyphs/winxp-icon-file-pdf.png",
    "file-json": "glyphs/winxp-icon-file-json.png"
  },
  "strips": {
    "titlebar": "strips/winxp-titlebar.png",
    "titlebar/inactive": "strips/winxp-titlebar_inactive.png",
    "toolbar": "strips/winxp-toolbar.png",
    "sidebar": "strips/winxp-sidebar.png",
    "sidebar-heading": "strips/winxp-sidebar-heading.png",
    "segment": "strips/winxp-segment.png",
    "segment/selected": "strips/winxp-segment_selected.png",
    "button": "strips/winxp-button.png"
  },
  "fonts": {
    "regular": "shell:font.w95fa.0",
    "bold": "shell:font.w95fa.7"
  },
  "chrome": {
    "side": "right",
    "order": [
      "minimize",
      "zoom",
      "close"
    ]
  }
};
