// GENERATED by tools/cook-themes.ts — do not edit.
// Values: themes-src/sheru/xfce.json (sheru 49d35621ae5b) + themes-src/density.ts
// Rules:  themes-src/paint/xfce.ts
import type { ThemeSkin } from "../skin.ts";

export const xfceSkin: ThemeSkin = {
  "id": "xfce",
  "name": "XFCE",
  "classes": {
    "desktop": "w-full h-full flex-col justify-center items-center bg-[#5a7d9a]",
    "window": "w-[464] h-[256] flex-col rounded-[4] border-[#555c63] bg-gradient-to-b from-[#cecece] to-[#d6d6d6]",
    "window-frame": "flex-1 flex-col",
    "window-frame-edge": "absolute inset-0",
    "titlebar": "flex-row items-center justify-between h-[18] pt-[0] pr-[4] pb-[0] pl-[4] bg-gradient-to-b from-[#4a525a] to-[#3c434a]",
    "titlebar/inactive": "flex-row items-center justify-between h-[18] pt-[0] pr-[4] pb-[0] pl-[4] bg-gradient-to-b from-[#888888] to-[#777777]",
    "title": "pt-[0] pr-[4] pb-[0] pl-[4] text-xs font-bold text-[#ffffff]",
    "title/inactive": "pt-[0] pr-[4] pb-[0] pl-[4] text-xs font-bold text-[#cccccc]",
    "controls": "flex-row items-center pt-[0] pr-[2] pb-[0] pl-[2] gap-[2]",
    "control": "w-[25] h-[18] flex-col justify-center items-center rounded-[3] focus:bg-[#ffffff2e] active:bg-[#00000038]",
    "control/close": "w-[25] h-[18] flex-col justify-center items-center rounded-[3] focus:bg-[#cc575d] active:bg-[#cc575d]",
    "toolbar": "flex-row items-center h-[26] pt-[0] pr-[4] pb-[0] pl-[4] bg-gradient-to-b from-[#d8d8d8] to-[#cbcbcb] gap-[4]",
    "toolbar-button": "flex-col justify-center items-center h-[22] pt-[0] pr-[5] pb-[0] pl-[5] rounded-[3] focus:bg-gradient-to-b focus:from-[#ffffff] focus:to-[#e8e8e8] text-xs font-bold text-[#212121] min-w-[22] active:bg-[#d4d4d4]",
    "breadcrumbs": "flex-1 flex-row items-center h-[20] pt-[2] pr-[4] pb-[2] pl-[4] rounded-[3] border-[#bcbcbc] bg-[#ffffff]",
    "breadcrumb": "pt-[0] pr-[3] pb-[0] pl-[3] text-xs text-[#212121]",
    "split": "flex-1 flex-row p-[2] gap-[2] overflow-hidden",
    "sidebar": "flex-col w-[96] p-[2] border-[#bcbcbc] bg-[#f2f1f0] overflow-hidden",
    "sidebar-heading": "flex-row items-center h-[16] pt-[0] pr-[6] pb-[0] pl-[6] text-xs text-[#666666] mb-[2] shrink-0",
    "sidebar-item": "flex-row items-center h-[17] pt-[0] pr-[4] pb-[0] pl-[4] rounded-[3] focus:bg-gradient-to-b focus:from-[#5d9fcd] focus:to-[#4a90c2] shrink-0",
    "file-list": "flex-1 flex-col border-[#bcbcbc] bg-[#ffffff] overflow-hidden",
    "file-list-header": "flex-row items-center h-[17] shrink-0",
    "file-list-col": "flex-row items-center h-full pt-[0] pr-[6] pb-[0] pl-[6] border-[#bcbcbc] bg-gradient-to-b from-[#f4f4f4] to-[#dfdfdf] text-xs text-[#212121]",
    "file-list-col/sorted": "flex-row items-center h-full pt-[0] pr-[6] pb-[0] pl-[6] border-[#bcbcbc] bg-[#d4d4d4] text-xs text-[#212121]",
    "file-row": "flex-row items-center h-[17] pt-[0] pr-[2] pb-[0] pl-[2] focus:bg-gradient-to-b focus:from-[#5d9fcd] focus:to-[#4a90c2] shrink-0",
    "status-bar": "flex-row items-center h-[20] p-[2] bg-[#d9d9d9] gap-[2] shrink-0",
    "status-item": "flex-row items-center h-full pt-[0] pr-[6] pb-[0] pl-[6] text-xs text-[#212121]",
    "button": "h-[22] flex-col justify-center items-center pt-[0] pr-[10] pb-[0] pl-[10] rounded-[3] border-[#999999] bg-gradient-to-b from-[#fcfcfc] to-[#dedede] text-xs text-[#212121]",
    "segment": "flex-col justify-center items-center h-[22] w-[33] border-[#999999] bg-gradient-to-b from-[#fcfcfc] to-[#dedede]",
    "segment/selected": "flex-col justify-center items-center h-[22] w-[33] border-[#999999] bg-[#d4d4d4]"
  },
  "metrics": {
    "windowFrameW": 0,
    "controlW": 25,
    "controlH": 18
  },
  "glyphs": {
    "minimize": "glyphs/xfce-minimize.png",
    "zoom": "glyphs/xfce-zoom.png",
    "close": "glyphs/xfce-close.png",
    "folder": "glyphs/xfce-icon-folder.png",
    "file": "glyphs/xfce-icon-file.png",
    "file-md": "glyphs/xfce-icon-file-md.png",
    "file-png": "glyphs/xfce-icon-file-png.png",
    "file-pbp": "glyphs/xfce-icon-file-pbp.png",
    "file-xlsx": "glyphs/xfce-icon-file-xlsx.png",
    "file-txt": "glyphs/xfce-icon-file-txt.png",
    "file-pdf": "glyphs/xfce-icon-file-pdf.png",
    "file-json": "glyphs/xfce-icon-file-json.png"
  },
  "strips": {},
  "fonts": {
    "regular": "shell:font.inter.0",
    "bold": "shell:font.inter.7"
  },
  "chrome": {
    "side": "right",
    "order": [
      "minimize",
      "zoom",
      "close"
    ]
  }
};
