// Cook themes: sheru snapshot (values) + paint spec (rules) + density →
// app/theme/cooked/<id>.cooked.ts, a table of full PocketJS class literals
// keyed by "part" / "part/state".
//
// Lowerings (tools/cook-lib.ts):
//   - token refs / var() chains / rgba() → resolved hex/px against the
//     snapshot tokens (themes-src/density.ts overrides applied first)
//   - 2-stop axis linear-gradient → native gradient utilities; anything
//     richer (multi-stop, alpha stops via rgba(), non-axis) → a baked strip
//     image request (themes-src/strips.json, rendered by <GradientStrip>)
//   - box-shadow bevel stacks → bevel-[...] utilities
//   - radius/border/shadow → rounded-[N] / border-[#hex] / shadow*
//
// Every emitted literal round-trips through the VENDORED tailwind compiler;
// any unparseable literal fails the cook. Cooked files are committed and
// scanned by the app build, so the runtime does zero style work.
//
//   bun tools/cook-themes.ts

import { mkdirSync } from "node:fs";
import type { PaintSpec } from "../themes-src/types.ts";
import { cookTheme, type StripRequest } from "./cook-lib.ts";
import { win98Paint } from "../themes-src/paint/win98.ts";
import { winxpPaint } from "../themes-src/paint/winxp.ts";
import { win7Paint } from "../themes-src/paint/win7.ts";
import { aquaPaint } from "../themes-src/paint/aqua.ts";
import { xfcePaint } from "../themes-src/paint/xfce.ts";

const repo = new URL("..", import.meta.url).pathname;
// SKINS cycle order in app.tsx: win98 -> winxp -> win7 -> aqua -> xfce.
const SPECS: PaintSpec[] = [win98Paint, winxpPaint, win7Paint, aquaPaint, xfcePaint];

// Known file extensions the mock data uses (per-ext badge icons).
const EXTS = ["md", "png", "pbp", "xlsx", "txt", "pdf", "json"];
// Era font per theme (bake-fonts.ts bakes these atlas pairs).
const FONTS: Record<string, string> = {
  win98: "w95fa",
  winxp: "w95fa",
  win7: "inter",
  aqua: "inter",
  xfce: "inter",
};

mkdirSync(`${repo}app/theme/cooked`, { recursive: true });
const allStrips: StripRequest[] = [];

for (const spec of SPECS) {
  const snap = await Bun.file(`${repo}themes-src/sheru/${spec.id}.json`).json();
  const { classes, stripMap, strips } = await cookTheme(spec);
  allStrips.push(...strips);
  // Strip underlays inherit the part radius (a square strip image would
  // cover rounded corners — the aqua segments read as blue blocks).
  const stripEntries: Record<string, { src: string; cls: string }> = {};
  for (const [key, v] of Object.entries(stripMap)) {
    const [src, r] = (v as string).split("|");
    stripEntries[key] = { src, cls: r ? `absolute inset-0 rounded-[${r}]` : "absolute inset-0" };
  }

  const chrome = snap.theme.chrome;
  const glyphs: Record<string, string> = {};
  // Control artwork is keyed by the ACTIONS rendered (controlsOrder), not by
  // the symbol-glyph table — aqua ships an EMPTY glyphs object (bare gels at
  // rest) and its faces are baked separately by gen-assets.
  for (const name of chrome?.controlsOrder ?? ["minimize", "zoom", "close"]) {
    glyphs[name] = `glyphs/${spec.id}-${name}.png`;
  }
  glyphs.folder = `glyphs/${spec.id}-icon-folder.png`;
  glyphs.file = `glyphs/${spec.id}-icon-file.png`;
  for (const ext of EXTS) glyphs[`file-${ext}`] = `glyphs/${spec.id}-icon-file-${ext}.png`;

  const skin = {
    id: spec.id,
    name: snap.theme.name,
    classes,
    metrics: spec.metrics,
    glyphs,
    strips: stripEntries,
    fonts: {
      regular: `shell:font.${FONTS[spec.id]}.0`,
      bold: `shell:font.${FONTS[spec.id]}.7`,
    },
    chrome: {
      side: chrome?.controlsSide ?? "right",
      order: chrome?.controlsOrder ?? ["minimize", "zoom", "close"],
    },
  };

  const out =
    `// GENERATED by tools/cook-themes.ts — do not edit.\n` +
    `// Values: themes-src/sheru/${spec.id}.json (sheru ${snap.provenance.commit.slice(0, 12)}` +
    `${snap.provenance.dirty ? " +dirty" : ""}) + themes-src/density.ts\n` +
    `// Rules:  themes-src/paint/${spec.id}.ts\n` +
    `import type { ThemeSkin } from "../skin.ts";\n\n` +
    `export const ${spec.id}Skin: ThemeSkin = ${JSON.stringify(skin, null, 2)};\n`;
  await Bun.write(`${repo}app/theme/cooked/${spec.id}.cooked.ts`, out);
  console.log(
    `cooked ${spec.id}: ${Object.keys(classes).length} parts, ${strips.length} strips -> app/theme/cooked/${spec.id}.cooked.ts`,
  );
}

await Bun.write(`${repo}themes-src/strips.json`, JSON.stringify(allStrips, null, 2) + "\n");
console.log(`strips: ${allStrips.length} -> themes-src/strips.json`);
